### ISSUE TITLE
Bug "Invalid secret token"

### ISSUE THREAD

**Issue by AnthonyCodeDev** [MiniGlome/Tiktok_uploader#32]
def uploadVideo(session_id, video, title, tags, schedule_time=0, verbose=True):
    if schedule_time - datetime.datetime.now().timestamp() > 864000:  # 864000s = 10 days
        print("[-] Can not schedule video in more than 10 days")
        return False

    if verbose:
        print("Uploading video...", end='\r')

    session = requests.Session()
    session.cookies.set("sessionid", session_id, domain=".tiktok.com")

    # Initial requests to obtain necessary tokens
    url = "https://www.tiktok.com/upload/"
    r = session.get(url)
    if not assertSuccess(url, r):
        return False

    url = "https://www.tiktok.com/passport/web/account/info/"
    r = session.get(url)
    if not assertSuccess(url, r):
        return False
    user_id = r.json()["data"]["user_id_str"]

    url = "https://www.tiktok.com/api/v1/video/upload/auth/"
    r = session.get(url)
    if not assertSuccess(url, r):
        return False

    # Print the JSON response for debugging
    print("Video upload auth response:", r.json())

    # Extract the necessary keys and tokens
    video_token = r.json().get("video_token_v5", {})
    access_key = video_token.get("access_key_id")
    secret_key = video_token.get("secret_acess_key")
    session_token = video_token.get("session_token")

    # Verify that all keys are retrieved correctly
    if not access_key or not secret_key or not session_token:
        print("[-] Missing one or more tokens: access_key, secret_key, session_token")
        return False

    with open(video, "rb") as f:
        video_content = f.read()
    file_size = len(video_content)

    url = "https://vod-us-east-1.bytevcloudapi.com/"
    request_parameters = f'Action=ApplyUploadInner&FileSize={file_size}&FileType=video&IsInner=1&SpaceName=tiktok&Version=2020-11-19&s=zdxefu8qvq8'
    t = datetime.datetime.utcnow()
    amzdate = t.strftime('%Y%m%dT%H%M%SZ')
    datestamp = t.strftime('%Y%m%d')
    headers = {  # Must be in alphabetical order, keys in lower case
        "x-amz-date": amzdate,
        "x-amz-security-token": session_token
    }
    signature = AWSsignature(access_key, secret_key, request_parameters, headers)
    authorization = f"AWS4-HMAC-SHA256 Credential={access_key}/{datestamp}/us-east-1/vod/aws4_request, SignedHeaders=x-amz-date;x-amz-security-token, Signature={signature}"
    headers["authorization"] = authorization
    r = session.get(f"{url}?{request_parameters}", headers=headers)

    # Print the JSON response for debugging
    print("ApplyUploadInner response:", r.json())

    if not assertSuccess(url, r):
        return False

    if 'Result' not in r.json():
        print("[-] 'Result' key not found in response")
        return False

    upload_node = r.json()["Result"]["InnerUploadAddress"]["UploadNodes"][0]
    video_id = upload_node["Vid"]
    store_uri = upload_node["StoreInfos"][0]["StoreUri"]
    video_auth = upload_node["StoreInfos"][0]["Auth"]
    upload_host = upload_node["UploadHost"]
    session_key = upload_node["SessionKey"]

Console response:
Video upload auth response: {'ak': 'b', 'audio_token_v5': {'access_key_id': 'a', 'current_time': '2024-06-17T14:44:54Z', 'expired_time': '2024-06-26T08:44:54Z', 'secret_acess_key': 'a', 'session_token': 'b=', 'space_name': 'tt_audio_mode'}, 'auth': 'd', 'extra': {'fatal_item_ids': [], 'logid': 'v', 'now': 1718635494000}, 'log_pb': {'impr_id': 'e'}, 'status_code': 0, 'status_msg': '', 'store_region': 'FR', 'video_token_v5': {'access_key_id': 'f', 'current_time': '2024-06-17T14:44:54Z', 'expired_time': '2024-07-17T14:44:54Z', 'secret_acess_key': 'g', 'session_token': 't=', 'space_name': 'tiktok'}}
ApplyUploadInner response: {'ResponseMetadata': {'RequestId': 'g', 'Action': 'ApplyUploadInner', 'Version': '2020-11-19', 'Service': 'vod', 'Region': 'us-east-1', 'Error': {'CodeN': 100026, 'Code': 'InvalidSecretToken', 'Message': 'Invalid secret token, msg: %s.'}}}
[-] 'Result' key not found in response

"Invalid secret token" while I put the correct sessionid from tiktok;

**Comment by holzhaker1** [comment]
Did you find any fix for this or is this just closed because it was open too long?
